routes/web.php
<?php

use App\Http\Controllers\UserActivityController;
use App\Http\Controllers\UserLocationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UptController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->group(function () {
    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('login', [LoginController::class, 'index']);

    Route::post('login', [LoginController::class, 'login'])->name('login');
});

Route::middleware('auth')->group(function () {
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::prefix('dashboard')->name('dashboard.')->group(function ()
    {
        Route::resource('upt', UptController::class);

        Route::resource('petugas', UserController::class);

        Route::resource('lokasi-petugas', UserLocationController::class);

        Route::resource('laporan-aktivitas', UserActivityController::class);

        Route::resource('pencarian', SearchController::class);
    });
});


// Route::prefix('laravel-filemanager')->middleware(['web', 'auth'])->group(function ()
// {
//     \UniSharp\LaravelFilemanager\Lfm::routes();
// });

app/Models/Upt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Upt extends Model
{
    use HasFactory;

    protected $guarded = [
        'id'
    ];

    public function upt_organizational_structures()
    {
        return $this->hasMany('App\Models\UptOrganizationalStructure');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data['title'] = 'Beranda';

        return view('dashboard.index', $data);
    }
}

app/Http/Controllers/UptController.php
<?php

namespace App\Http\Controllers;

use App\Models\Upt;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UptController extends Controller
{
    public function index(Request $request)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('upt_read', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'UPT';
        $data['upts'] = Upt::where('name', 'LIKE', '%'.$request->search.'%')->orWhere('description', 'LIKE', '%'.$request->search.'%')->orderBy('name')->paginate(5);

        return view('dashboard.upt.index', $data);
    }

    public function create()
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('upt_create', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Tambah UPT';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.upt.index'),
                'name' => 'UPT'
            ]
        ];
        return view('dashboard.upt.create', $data);
    }

    public function store(Request $request)
    {
        $img = $this->storeFile($request);
        Upt::create([
            'name' => $request->name,
            'description' => $request->description,
            'img_organizational_structure' => $img
        ]);

        return redirect()->back()->with('OK', 'Data berhasil ditambah');
    }

    public function show($id)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('upt_read', $userPermissions)) {
            return abort(404);
        }
        $data['upt'] = Upt::findOrFail($id);
        $data['title'] = 'Detail UPT';

        return view('dashboard.upt.show', $data);
    }

    public function edit($id)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('upt_update', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Edit UPT';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.upt.index'),
                'name' => 'UPT'
            ]
        ];
        $data['upt'] =  Upt::findOrFail($id);
        return view('dashboard.upt.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $upt =  Upt::findOrFail($id);

        $img = $this->storeFile($request) ?? $upt->img_organizational_structure;
        $upt->update([
            'name' => $request->name,
            'description' => $request->description,
            'img_organizational_structure' => $img
        ]);

        return redirect()->back()->with('OK', 'Data berhasil diperbarui');
    }

    public function destroy($id)
    {
        $upt =  Upt::findOrFail($id);
        $upt->delete();

        return redirect()->back()->with('OK', 'Data berhasil dihapus');
    }

    public function storeFile(Request $request)
    {
        if(!$request->hasFile('file'))
        {
            return null;
        }

        $fileName = time().'_'.$request->file->getClientOriginalName();
        $filePath = $request->file('file')->storeAs('uploads/upt', $fileName, 'public');

        return '/storage/' . $filePath;
    }
}

resources/views/dashboard/upt/create.blade.php
@extends('layouts.master')

@section('style')
    <style>
        .img-preview-wrapper{
            border: 2px dashed #5A8EEE !important;
            padding: 24px;
        }

        .img-preview-wrapper img{
            max-width: 372px;
        }

        @media only screen and (max-width: 600px)
        {
            .img-preview-wrapper{
                padding: 12px !important;
            }
            .img-preview-wrapper img{
                max-width: 100% !important;
            }
        }
    </style>
@endsection

@section('content')
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form action="{{ route('dashboard.upt.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="">Gambar Struktur Organisasi</label>
                                <div class="img-preview-wrapper text-center mb-1">
                                    <img src="/app-assets/images/dropzone/empty.png" class="img-fluid">
                                </div>
                                <input name="file" type="file" class="form-control input-image" accept="image/*" required>
                            </div>
                            <div class="form-group">
                                <label for="">NAMA UPT</label>
                                <input name="name" type="text" class="form-control" placeholder="cth: John Doe" required>
                            </div>
                            <div class="form-group">
                                <label for="">DESKRIPSI</label>
                                <textarea name="description" class="form-control" rows="6" required></textarea>
                            </div>
                            <div class="form-group mb-0 text-right">
                                <button class="btn btn-primary">
                                    <i class="bx bx-save"></i>
                                    <span class="align-middle ml-25">Simpan</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("a[href='{{ route('dashboard.upt.index') }}']").closest("li").addClass("active");

        $(document).on("change", ".input-image", function()
        {
            const [file] = $(this)[0].files
            console.log(file);
            if (file) {
                let img = URL.createObjectURL(file);
                console.log(img);
                $(this).siblings(".img-preview-wrapper").find("img").prop("src", img);
            }
        });
    </script>
@endsection

resources/views/dashboard/upt/edit.blade.php
@extends('layouts.master')

@section('style')
    <style>
        .img-preview-wrapper{
            border: 2px dashed #5A8EEE !important;
            padding: 24px;
        }

        .img-preview-wrapper img{
            max-width: 372px;
        }

        @media only screen and (max-width: 600px)
        {
            .img-preview-wrapper{
                padding: 12px !important;
            }
            .img-preview-wrapper img{
                max-width: 100% !important;
            }
        }
    </style>
@endsection

@section('content')
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form action="{{ route('dashboard.upt.update', $upt->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method("PUT")
                            <div class="form-group">
                                <label for="">Gambar Struktur Organisasi</label>
                                <div class="img-preview-wrapper text-center mb-1">
                                    <img src="{{ $upt->img_organizational_structure }}" class="img-fluid">
                                </div>
                                <input name="file" type="file" class="form-control input-image" accept="image/*">
                            </div>
                            <div class="form-group">
                                <label for="">NAMA UPT</label>
                                <input name="name" type="text" class="form-control" placeholder="cth: John Doe" value="{{ $upt->name }}" required>
                            </div>
                            <div class="form-group">
                                <label for="">DESKRIPSI</label>
                                <textarea name="description" class="form-control" rows="6" required>{{ $upt->description }}</textarea>
                            </div>
                            <div class="form-group mb-0 text-right">
                                <button class="btn btn-primary">
                                    <i class="bx bx-save"></i>
                                    <span class="align-middle ml-25">Simpan</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("a[href='{{ route('dashboard.upt.index') }}']").closest("li").addClass("active");

        $(document).on("change", ".input-image", function()
        {
            const [file] = $(this)[0].files
            console.log(file);
            if (file) {
                let img = URL.createObjectURL(file);
                console.log(img);
                $(this).siblings(".img-preview-wrapper").find("img").prop("src", img);
            }
        });
    </script>
@endsection

resources/views/dashboard/upt/index.blade.php
@php
    $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
@endphp

@extends('layouts.master')

@section('style')

@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="search-bar-wrapper">
                <div class="search-bar">
                    <!-- input search -->
                    <form>
                        <fieldset class="page-search-input form-group position-relative">
                            <input name="search" type="text" class="form-control rounded-right form-control-lg shadow pl-2" id="searchbar" placeholder="Search">
                            <button class="btn btn-primary search-btn rounded" type="submit">
                                <i class="bx bx-search align-middle"></i>
                                <span class="d-none d-sm-inline-block align-middle">Search</span>
                            </button>
                        </fieldset>
                    </form>
                    <!--/ input search -->
                </div>
            </div>
        </div>
    </div>

    @if (in_array('upt_create', $userPermissions))
        <div class="row mt-1">
            <div class="col-12 text-right">
                <a href="{{ route('dashboard.upt.create') }}" class="btn btn-primary text-uppercase">
                    <i class="bx bx-plus"></i>
                    <span class="align-middle ml-25">Tambah</span>
                </a>
            </div>
        </div>
    @endif

    @foreach ($upts as $key => $upt)
        <div class="row mt-2">
            <div class="col-12">
                <div class="card mb-0">
                    <div class="card-header">
                        <h4 class="card-title">{{ $upt->name }} </h4>
                        <a class="heading-elements-toggle">
                            <i class="bx bx-dots-vertical font-medium-3"></i>
                        </a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0 p-1 p-md-0">
                                <li>
                                    <a href="{{ route('dashboard.upt.show', $upt->id) }}" class="text-uppercase">
                                        <i class="bx bx-expand align-middle"></i>
                                        <span class="align-middle ml-25">Detail</span>
                                    </a>
                                </li>
                                @if (in_array('upt_update', $userPermissions))
                                    <li class="ml-1">
                                        <a href="{{ route('dashboard.upt.edit', $upt->id) }}" class="text-uppercase">
                                            <i class="bx bx-edit align-middle"></i>
                                            <span class="align-middle ml-25">Edit</span>
                                        </a>
                                    </li>
                                @endif
                                @if (in_array('upt_delete', $userPermissions))
                                    <li class="ml-1">
                                        <a href="javascript:;" class="text-uppercase btn-delete">
                                            <i class="bx bx-trash align-middle"></i>
                                            <span class="align-middle ml-25">Hapus</span>
                                            <form action="{{ route('dashboard.upt.destroy', $upt->id) }}" method="POST">
                                                @csrf
                                                @method("DELETE")
                                            </form>
                                        </a>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <p class="text-justify" style="white-space: pre-wrap">{{ $upt->description }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            {{ $upts->links() }}
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).on('click', '.btn-delete', function () {
            let form = $(this).find('form');
            showConfirmDialog('Data yang dihapus tidak dapat dikembalikan', () => {
                form.submit();
            });
        });
    </script>
@endsection

resources/views/dashboard/upt/show.blade.php
@extends('layouts.master')

@section('style')
    <style>
        .img-preview-wrapper{
            padding: 24px;
        }

        .img-preview-wrapper img{
            max-width: 372px;
        }

        @media only screen and (max-width: 600px)
        {
            .img-preview-wrapper{
                padding: 12px !important;
            }
            .img-preview-wrapper img{
                max-width: 100% !important;
            }
        }
    </style>
@endsection

@section('content')
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $upt->name }}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div class="form-group">
                            <div class="img-preview-wrapper text-center mb-1">
                                <img src="{{ $upt->img_organizational_structure }}" class="img-fluid">
                            </div>
                        </div>
                        <div class="form-group" style="white-space: pre">{{ $upt->description }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("a[href='{{ route('dashboard.upt.index') }}']").closest("li").addClass("active");
    </script>
@endsection