routes/web.php
<?php

use App\Http\Controllers\UserActivityController;
use App\Http\Controllers\UserLocationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UptController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->group(function () {
    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('login', [LoginController::class, 'index']);

    Route::post('login', [LoginController::class, 'login'])->name('login');
});

Route::middleware('auth')->group(function () {
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::prefix('dashboard')->name('dashboard.')->group(function ()
    {
        Route::resource('upt', UptController::class);

        Route::resource('petugas', UserController::class);

        Route::resource('lokasi-petugas', UserLocationController::class);

        Route::resource('laporan-aktivitas', UserActivityController::class);

        Route::resource('pencarian', SearchController::class);
    });
});


// Route::prefix('laravel-filemanager')->middleware(['web', 'auth'])->group(function ()
// {
//     \UniSharp\LaravelFilemanager\Lfm::routes();
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $guarded = [
        'id'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo('App\Models\Role');
    }

    public function user_permissions()
    {
        return $this->hasMany('App\Models\UserPermission');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data['title'] = 'Beranda';

        return view('dashboard.index', $data);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use App\Models\UserActivity;
use App\Models\UserPermission;
use DateInterval;
use DatePeriod;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use IntlDateFormatter;

class UserController extends Controller
{
    public function index()
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_read', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Petugas';
        $data['roles'] = Role::with('users')->get();

        return view('dashboard.user.index', $data);
    }

    public function create()
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_create', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Tambah Petugas';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.petugas.index'),
                'name' => 'Petugas'
            ]
        ];
        $data['roles'] = Role::all();

        return view('dashboard.user.create', $data);
    }

    public function store(Request $request)
    {
        $existingEmail = User::where('email', $request->email)->first();
        if ($existingEmail != null)
        {
            return redirect()->back()->with('ERR', 'Email tidak dapat digunakan');
        }

        $user = User::create([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'password' => bcrypt($request->password),
            'role_id' => $request->role_id,
            'status' => $request->status
        ]);

        if (isset($request->permissions))
        {
            $permissions = [];
            foreach ($request->permissions as $permission)
            {
                $permission = [
                    'user_id' => $user->id,
                    'permission' => $permission,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ];
                array_push($permissions, $permission);
            }

            UserPermission::insert($permissions);
        }

        return redirect()->back()->with('OK', 'Data berhasil ditambah');
    }

    public function show(Request $request, $id)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('upt_read', $userPermissions)) {
            return abort(404);
        }
        $dates = [];
        $dateNames = [];
        $startDate = $request->start_date ?? date('Y-m-d', strtotime('-5 days'));
        $endDate = $request->end_date ?? date('Y-m-d');
        $dateFormat = new IntlDateFormatter('id_ID',  IntlDateFormatter::NONE,
        IntlDateFormatter::NONE, NULL, NULL, "dd MMMM YYYY");
        $period = new DatePeriod(
            new DateTime($startDate),
            new DateInterval('P1D'),
            new DateTime(date('Y-m-d', strtotime($endDate . ' +1 days')))
        );
        $totalActivities = [];
        $totalTimes = [];
        foreach ($period as $value) {
            $date = $value->format('Y-m-d');
            $dateName = datefmt_format($dateFormat, strtotime($date));
            array_push($dates, $date);
            array_push($dateNames, $dateName);
            array_push($totalActivities, 0);
            array_push($totalTimes, 0);
        }
        $activities = UserActivity::with('user')->where('user_id', $id)->whereDate('date', '>=', $startDate)->whereDate('date', '<=', $endDate)->get();
        foreach ($activities as $key => $activity) {
            $dateIndex = array_search($activity->date, $dates);
            $totalActivities[$dateIndex] = ($totalActivities[$dateIndex] ?? 0) + 1;
            $totalTimes[$dateIndex] = ($totalTimes[$dateIndex] ?? 0) + $activity->diff_in_hours;
            $activity['date_name'] = $dateNames[$dateIndex];
            $activities[$key] = $activity;
        }

        $data['dates'] = $dates;
        $data['date_names'] = $dateNames;
        $data['activities'] = collect($activities);
        $data['total_activities'] = collect($totalActivities)->values();
        $data['total_times'] = collect($totalTimes)->values();

        $data['user'] = User::findOrFail($id);
        $data['title'] = 'Detail Petugas';

        return view('dashboard.user.show', $data);
    }

    public function edit($id)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_update', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Edit Petugas';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.petugas.index'),
                'name' => 'Petugas'
            ]
        ];
        $data['roles'] = Role::all();
        $data['user'] = User::with('user_permissions')->findOrFail($id);

        return view('dashboard.user.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $existingEmail = User::where('email', $request->email)->first();
        if ($existingEmail != null)
        {
            if ($user->id != $existingEmail->id)
            {
                return redirect()->back()->with('ERR', 'Email tidak dapat digunakan');
            }
        }
        $password = $request->password != null && $request->password != '' ? bcrypt($request->password) : $user->password;
        $user->update([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'password' => $password,
            'role_id' => $request->role_id,
            'status' => $request->status
        ]);

        UserPermission::where('user_id', $user->id)->delete();
        if (isset($request->permissions))
        {
            $permissions = [];
            foreach ($request->permissions as $permission)
            {
                $permission = [
                    'user_id' => $user->id,
                    'permission' => $permission,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ];
                array_push($permissions, $permission);
            }

            UserPermission::insert($permissions);
        }

        return redirect()->back()->with('OK', 'Data berhasil diperbarui');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->back()->with('OK', 'Data berhasil dihapus');
    }
}

resources/views/dashboard/user/index.blade.php
@php
    $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
@endphp

@extends('layouts.master')

@section('style')

@endsection

@section('content')

    @if (in_array('user_create', $userPermissions))
        <div class="row">
            <div class="col-12 text-right">
                <a href="{{ route('dashboard.petugas.create') }}" class="btn btn-primary text-uppercase">
                    <i class="bx bx-plus"></i>
                    <span class="align-middle ml-25">Tambah</span>
                </a>
            </div>
        </div>
    @endif

    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
                            @foreach ($roles as $key => $role)
                                <li class="nav-item">
                                    <a class="nav-link {{ $key == 0 ? 'active' : '' }}" id="{{ str_replace(' ', '-', $role->name) }}-label" data-toggle="tab" href="#{{ str_replace(' ', '-', $role->name) }}" role="tab" aria-controls="{{ str_replace(' ', '-', $role->name) }}">
                                        {{ strtoupper($role->name) }}
                                    </a>
                                </li>
                            @endforeach
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content pt-1">
                            @foreach ($roles as $key => $role)
                                <div class="tab-pane {{ $key == 0 ? 'active' : '' }}" id="{{ str_replace(' ', '-', $role->name) }}" role="tabpanel" aria-labelledby="{{ str_replace(' ', '-', $role->name) }}-label">
                                    <table class="table datatable w-100 table-responsive">
                                        <thead>
                                            <tr>
                                                <th>NO</th>
                                                <th>NAMA</th>
                                                <th>ALAMAT EMAIL</th>
                                                <th class="text-nowrap">NOMOR TELEPON</th>
                                                <th class="text-center" style="width: 1%">AKSI</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($role->users as $user)
                                                <tr>
                                                    <td></td>
                                                    <td class="text-nowrap">{{ $user->name }}</td>
                                                    <td>{{ $user->email }}</td>
                                                    <td class="text-nowrap">{{ $user->phone_number }}</td>
                                                    <td class="text-nowrap">
                                                        <div class="btn-group btn-group-sm">
                                                            <a href="{{ route('dashboard.petugas.show', $user->id) }}" class="btn btn-primary text-uppercase">
                                                                <i class="bx bx-expand"></i>
                                                                <span class="ml-25">detail</span>
                                                            </a>
                                                            @if (in_array('user_update', $userPermissions))
                                                                <a href="{{ route('dashboard.petugas.edit', $user->id) }}" class="btn btn-info text-uppercase">
                                                                    <i class="bx bx-edit"></i>
                                                                    <span class="ml-25">edit</span>
                                                                </a>
                                                            @endif
                                                            @if (in_array('user_delete', $userPermissions))
                                                                <a href="javascript:;" class="btn btn-danger text-uppercase btn-delete">
                                                                    <i class="bx bx-trash"></i>
                                                                    <span class="ml-25">Hapus</span>
                                                                    <form action="{{ route('dashboard.petugas.destroy', $user->id) }}" method="POST" class="align-middle">
                                                                        @csrf
                                                                        @method("DELETE")
                                                                    </form>
                                                                </a>
                                                            @endif
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @endforeach
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).on('click', '.btn-delete', function () {
            let form = $(this).find('form');
            showConfirmDialog('Data yang dihapus tidak dapat dikembalikan', () => {
                form.submit();
            });
        });
    </script>
@endsection