routes/web.php
<?php

use App\Http\Controllers\UserActivityController;
use App\Http\Controllers\UserLocationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UptController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->group(function () {
    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('login', [LoginController::class, 'index']);

    Route::post('login', [LoginController::class, 'login'])->name('login');
});

Route::middleware('auth')->group(function () {
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::prefix('dashboard')->name('dashboard.')->group(function ()
    {
        Route::resource('upt', UptController::class);

        Route::resource('petugas', UserController::class);

        Route::resource('lokasi-petugas', UserLocationController::class);

        Route::resource('laporan-aktivitas', UserActivityController::class);

        Route::resource('pencarian', SearchController::class);
    });
});


// Route::prefix('laravel-filemanager')->middleware(['web', 'auth'])->group(function ()
// {
//     \UniSharp\LaravelFilemanager\Lfm::routes();
// });

app/Models/UserActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserActivity extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data['title'] = 'Beranda';

        return view('dashboard.index', $data);
    }
}

app/Http/Controllers/UserActivityController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserActivity;
use Carbon\Carbon;
use DateInterval;
use DatePeriod;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use IntlDateFormatter;

class UserActivityController extends Controller
{
    public function index(Request $request)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_activity_read', $userPermissions)) {
            return abort(404);
        }
        setlocale(LC_ALL, 'id-ID', 'id_ID');
        $data['users'] = User::all();

        $data['title'] = 'Laporan Aktivitas';
        $dates = [];
        $dateNames = [];
        $startDate = $request->start_date ?? date('Y-m-d', strtotime('-5 days'));
        $endDate = $request->end_date ?? date('Y-m-d');
        $dateFormat = new IntlDateFormatter('id_ID',  IntlDateFormatter::NONE,
        IntlDateFormatter::NONE, NULL, NULL, "dd MMMM YYYY");
        $period = new DatePeriod(
            new DateTime($startDate),
            new DateInterval('P1D'),
            new DateTime(date('Y-m-d', strtotime($endDate . ' +1 days')))
        );
        $totalActivities = [];
        $totalTimes = [];
        foreach ($period as $value) {
            $date = $value->format('Y-m-d');
            $dateName = datefmt_format($dateFormat, strtotime($date));
            array_push($dates, $date);
            array_push($dateNames, $dateName);
            array_push($totalActivities, 0);
            array_push($totalTimes, 0);
        }
        $activities = UserActivity::with('user')->where(function($q) use($request, $userPermissions)
        {
            if (!in_array('user_activity_fulldata', $userPermissions)) {
                $q->where('user_id', Auth::user()->id);
            }
            if (in_array('user_activity_fulldata', $userPermissions) && $request->user_id != null) {
                $q->where('user_id', $request->user_id);
            }
        })->whereDate('date', '>=', $startDate)->whereDate('date', '<=', $endDate)->get();
        foreach ($activities as $key => $activity) {
            $dateIndex = array_search($activity->date, $dates);
            $totalActivities[$dateIndex] = ($totalActivities[$dateIndex] ?? 0) + 1;
            $totalTimes[$dateIndex] = ($totalTimes[$dateIndex] ?? 0) + $activity->diff_in_hours;
            $activity['date_name'] = $dateNames[$dateIndex];
            $activities[$key] = $activity;
        }

        $data['dates'] = $dates;
        $data['date_names'] = $dateNames;
        $data['activities'] = collect($activities);
        $data['total_activities'] = collect($totalActivities)->values();
        $data['total_times'] = collect($totalTimes)->values();

        return view('dashboard.user-activity.index', $data);
    }

    public function create()
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_activity_create', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Tambah Laporan Aktivitas';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.laporan-aktivitas.index'),
                'name' => 'Laporan Aktivitas'
            ]
        ];
        $isAllowedFullData = Auth::user()->user_permissions->where('permission', 'user_activity_fulldata')->first();
        $data['users'] = User::where(function($q) use($isAllowedFullData)
        {
            if ($isAllowedFullData == null) {
                $q->where('id', Auth::user()->id);
            }
        })->get();

        return view('dashboard.user-activity.create', $data);
    }

    public function store(Request $request)
    {
        $startDate = Carbon::createFromFormat('Y-m-d H:i', $request->date. ' ' .$request->start_time);
        $endDate = Carbon::createFromFormat('Y-m-d H:i', $request->date. ' ' .$request->end_time);
        $diffInHours = $startDate->diffInHours($endDate);
        UserActivity::create([
            'user_id' => $request->user_id,
            'date' => $request->date,
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'diff_in_hours' => $diffInHours,
            'activity' => $request->activity,
            'notes' => $request->notes,
        ]);

        return redirect()->back()->with('OK', 'Data berhasil ditambah');
    }

    public function edit($id)
    {
        $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
        if (!in_array('user_activity_update', $userPermissions)) {
            return abort(404);
        }
        $data['title'] = 'Edit Laporan Aktivitas';
        $data['content_headers'] = [
            (object)[
                'url' => route('dashboard.laporan-aktivitas.index'),
                'name' => 'Laporan Aktivitas'
            ]
        ];
        $isAllowedFullData = empty(Auth::user()->user_permissions->where('permission', 'user_activity_fulldata')->first());
        $data['users'] = User::where(function($q) use($isAllowedFullData)
        {
            if (!$isAllowedFullData) {
                $q->where('id', Auth::user()->id);
            }
        })->get();
        $data['activity'] = UserActivity::findOrFail($id);

        return view('dashboard.user-activity.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $startDate = Carbon::createFromFormat('Y-m-d H:i', $request->date. ' ' .$request->start_time);
        $endDate = Carbon::createFromFormat('Y-m-d H:i', $request->date. ' ' .$request->end_time);
        $diffInHours = $startDate->diffInHours($endDate);
        $userActivity = UserActivity::findOrFail($id);
        $userActivity->update([
            'user_id' => $request->user_id,
            'date' => $request->date,
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'diff_in_hours' => $diffInHours,
            'activity' => $request->activity,
            'notes' => $request->notes,
        ]);

        return redirect()->back()->with('OK', 'Data berhasil diperbarui');
    }

    public function destroy($id)
    {
        $userActivity = UserActivity::findOrFail($id);
        $userActivity->delete();

        return redirect()->back()->with('OK', 'Data berhasil dihapus');
    }
}

resources/views/dashboard/user-activity/create.blade.php
@extends('layouts.master')

@section('style')

@endsection

@section('content')
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form action="{{ route('dashboard.laporan-aktivitas.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="">NAMA</label>
                                <select name="user_id" class="form-control select2">
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group row">
                                <div class="col-12 col-md-4 mb-1 mb-md-0">
                                    <label for="">Tanggal</label>
                                    <input type="date" name="date" class="form-control" value="{{ date('Y-m-d') }}" required>
                                </div>
                                <div class="col-6 col-md-4 mb-1 mb-md-0">
                                    <label for="">Jam Mulai</label>
                                    <input type="time" name="start_time" class="form-control" required>
                                </div>
                                <div class="col-6 col-md-4">
                                    <label for="">Jam Selesai</label>
                                    <input type="time" name="end_time" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Aktivitas</label>
                                <input type="text" name="activity" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="">Catatan</label>
                                <textarea name="notes" class="form-control" rows="5"></textarea>
                            </div>
                            <div class="form-group mb-0 text-right">
                                <button class="btn btn-primary">
                                    <i class="bx bx-save"></i>
                                    <span class="align-middle ml-25">Simpan</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("a[href='{{ route('dashboard.laporan-aktivitas.index') }}']").closest("li").addClass("active");
    </script>
@endsection

resources/views/dashboard/user-activity/edit.blade.php
@extends('layouts.master')

@section('style')

@endsection

@section('content')
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form action="{{ route('dashboard.laporan-aktivitas.update', $activity->id) }}" method="post">
                            @csrf
                            @method("PUT")
                            <div class="form-group">
                                <label for="">NAMA</label>
                                <select name="user_id" class="form-control select2">
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}" {{ $activity->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group row">
                                <div class="col-12 col-md-4 mb-1 mb-md-0">
                                    <label for="">Tanggal</label>
                                    <input type="date" name="date" class="form-control" value="{{ $activity->date }}" required>
                                </div>
                                <div class="col-6 col-md-4 mb-1 mb-md-0">
                                    <label for="">Jam Mulai</label>
                                    <input type="time" name="start_time" class="form-control" value="{{ $activity->start_time }}" required>
                                </div>
                                <div class="col-6 col-md-4">
                                    <label for="">Jam Selesai</label>
                                    <input type="time" name="end_time" class="form-control" value="{{ $activity->end_time }}" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Aktivitas</label>
                                <input type="text" name="activity" class="form-control" value="{{ $activity->activity }}" required>
                            </div>
                            <div class="form-group">
                                <label for="">Catatan</label>
                                <textarea name="notes" class="form-control" rows="5">{{ $activity->notes }}</textarea>
                            </div>
                            <div class="form-group mb-0 text-right">
                                <button class="btn btn-primary">
                                    <i class="bx bx-save"></i>
                                    <span class="align-middle ml-25">Simpan</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("a[href='{{ route('dashboard.laporan-aktivitas.index') }}']").closest("li").addClass("active");
    </script>
@endsection

resources/views/dashboard/user-activity/index.blade.php
@php
    $userPermissions = Auth::user()->user_permissions->pluck('permission')->toArray();
@endphp

@extends('layouts.master')

@section('style')
    <style>
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-content collapse show">
                    <div class="card-body">
                        <form action="">
                            <div class="row">
                                @if (in_array('user_activity_fulldata', $userPermissions))
                                    <div class="col-md-3">
                                        <select name="user_id" id="" class="form-control select2">
                                            <option>Semua Petugas</option>
                                            @foreach ($users as $user)
                                                <option value="{{ $user->id }}" {{ request()->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                @endif
                                <div class="col-md-3">
                                    <input type="date" name="start_date" id="" class="form-control" value="{{ request()->start_date ?? date('Y-m-d') }}">
                                </div>
                                <div class="col-md-3">
                                    <input type="date" name="end_date" id="" class="form-control" value="{{ request()->end_date ?? date('Y-m-d') }}">
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="bx bxs-filter-alt"></i>
                                        <span class="align-middle ml-25">Filter</span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">Grafik Aktivitas</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div id="activity-chart"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-6">
            <div class="card mb-0">
                <div class="card-content collapse show">
                    <div class="card-body text-center">
                        <h1 class="text-primary">{{ count($activities) }}</h1>
                        <p>Total Aktivitas</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-0">
                <div class="card-content collapse show">
                    <div class="card-body text-center">
                        <h1 class="text-warning">{{ $activities->sum('diff_in_hours') }}</h1>
                        <p>Total Jam Kerja</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (in_array('user_activity_create', $userPermissions))
        <div class="row mt-2">
            <div class="col-12 text-right">
                <a href="{{ route('dashboard.laporan-aktivitas.create') }}" class="btn btn-primary text-uppercase">
                    <i class="bx bx-plus"></i>
                    <span class="align-middle ml-25">Tambah</span>
                </a>
            </div>
        </div>
    @endif
    <div class="row mt-1">
        <div class="col-12">
            <div class="card mb-0">
                <div class="card-header">
                    <h4 class="card-title">{{ $title }}</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <table class="table datatable w-100 table-responsive d-xl-table">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    @if (in_array('user_activity_fulldata', $userPermissions))
                                        <th>PETUGAS</th>
                                    @endif
                                    <th>TANGGAL</th>
                                    <th class="text-center">JAM</th>
                                    <th class="text-nowrap">AKTIVITAS</th>
                                    <th class="text-center" style="width: 1%">AKSI</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($activities as $activity)
                                    <tr>
                                        <td></td>
                                        @if (in_array('user_activity_fulldata', $userPermissions))
                                            <td>{{ $activity->user->name }}</td>
                                        @endif
                                        <td class="text-nowrap">{{ $activity->date_name }}</td>
                                        <td class="text-nowrap text-center">{{ $activity->start_time }} - {{ $activity->end_time }}</td>
                                        <td class="text-nowrap">{{ $activity->activity }}</td>
                                        <td class="text-nowrap">
                                            <div class="btn-group btn-group-sm">
                                                @if (in_array('user_activity_update', $userPermissions))
                                                    <a href="{{ route('dashboard.laporan-aktivitas.edit', $activity->id) }}" class="btn btn-info text-uppercase">
                                                        <i class="bx bx-edit"></i>
                                                        <span class="ml-25">Edit</span>
                                                    </a>
                                                @endif
                                                @if (in_array('user_activity_delete', $userPermissions))
                                                    <a href="javascript:;" class="btn btn-danger text-uppercase btn-delete">
                                                        <i class="bx bx-trash"></i>
                                                        <span class="ml-25">Hapus</span>
                                                        <form action="{{ route('dashboard.laporan-aktivitas.destroy', $activity->id) }}" method="POST" class="align-middle">
                                                            @csrf
                                                            @method("DELETE")
                                                        </form>
                                                    </a>
                                                @endif
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>


        $(document).on('click', '.btn-delete', function () {
            let deleteForm = $(this).find('form');
            showConfirmDialog('Data yang dihapus tidak dapat dikembalikan', () => {
                deleteForm.submit();
            });
        });

         // Line Area Chart
        // ----------------------------------
        var lineAreaOptions = {
            chart: {
                height: 400,
                type: 'bar',
                toolbar: {
                    show: false
                }
            },
            colors: ['#5A8DEE', '#FDAC41'],
            dataLabels: {
                enabled: false
            },
            stroke: {
                curve: 'smooth'
            },
            series: [
                {
                    name: 'Total Aktivitas',
                    data: @json($total_activities)
                },
                {
                    name: 'Total Jam Kerja',
                    data: @json($total_times)
                },
            ],
            legend: {
                offsetY: 8
            },
            xaxis: {
                categories: @json($date_names),
            },
            yaxis:{
                labels: {
                    formatter: (value) => {
                        return value.toFixed(0)
                    },
                }
            },
        }
        var lineAreaChart = new ApexCharts(
            document.querySelector("#activity-chart"),
            lineAreaOptions
        );
        lineAreaChart.render();
    </script>
@endsection